name: fbla_2023
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  google_generative_ai: ^0.4.3
  google_nav_bar: ^5.0.6
  flutter_gemini: ^2.0.4
  dash_chat_2: ^0.0.20
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  cupertino_icons: ^1.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/Logo.png
   - assets/images/google.png
   - assets/images/grade_point.png
