// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULXrxtx3N-nu_jsywAyHi8W2-G_6YeJg',
    appId: '1:156534679299:web:054972946d3dd032e6eb36',
    messagingSenderId: '156534679299',
    projectId: 'grade-point-8904a',
    authDomain: 'grade-point-8904a.firebaseapp.com',
    databaseURL: 'https://grade-point-8904a-default-rtdb.firebaseio.com',
    storageBucket: 'grade-point-8904a.appspot.com',
    measurementId: 'G-4JTPQG10RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSA-ZhcqUIqF9Ch1aibSgu1t3hUnpLCE',
    appId: '1:156534679299:android:449f0ebc75aae6c3e6eb36',
    messagingSenderId: '156534679299',
    projectId: 'grade-point-8904a',
    databaseURL: 'https://grade-point-8904a-default-rtdb.firebaseio.com',
    storageBucket: 'grade-point-8904a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdLCijJb0_TuJPRJCYRvNPVND-f90wLQ',
    appId: '1:156534679299:ios:ce511b66daa2c50ce6eb36',
    messagingSenderId: '156534679299',
    projectId: 'grade-point-8904a',
    databaseURL: 'https://grade-point-8904a-default-rtdb.firebaseio.com',
    storageBucket: 'grade-point-8904a.appspot.com',
    iosBundleId: 'com.example.fblaIntroToProgramming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTdLCijJb0_TuJPRJCYRvNPVND-f90wLQ',
    appId: '1:156534679299:ios:45776989deee4326e6eb36',
    messagingSenderId: '156534679299',
    projectId: 'grade-point-8904a',
    databaseURL: 'https://grade-point-8904a-default-rtdb.firebaseio.com',
    storageBucket: 'grade-point-8904a.appspot.com',
    iosBundleId: 'com.example.fblaIntroToProgramming.RunnerTests',
  );
}
